# Generated by Django 4.2.1 on 2023-05-25 10:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0002_version_snapshot_folder_change'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='document',
            options={'ordering': ['-title', '-created_at']},
        ),
    ]
