# Generated by Django 4.2.1 on 2023-05-25 19:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('document', '0003_alter_document_options'),
    ]

    operations = [
        migrations.AddField(
            model_name='version',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
    ]
